# -*- mode: ruby -*-
# vi: set ft=ruby :
HERE = File.join(File.dirname(__FILE__))

Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :hostonly, "192.168.199.101"
  config.vm.forward_port 5432, 5432
  config.vm.share_folder "setup", "/setup", "setup"
  config.vm.customize ["modifyvm", :id, "--memory", "384", "--name", "accidentalDBA"]
  config.vm.provision :shell, :path => "bootstrap.sh"
end
